import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <GoogleOAuthProvider clientId="593133685702-npmsdjhbr9lhusjjhh10144k3b1tf8q6.apps.googleusercontent.com">
      {children}
    </GoogleOAuthProvider>
        </body>
    </html>
  );
}
